### ISSUE TITLE
Does not look like the example in Pluto

### ISSUE THREAD

**Issue by ederag** [pfitzseb/ProfileCanvas.jl#11]
The example given in the README does not yield the same output here (and seems much less useful):
![Screenshot_20220528_134841](https://user-images.githubusercontent.com/10962809/170824207-46914ddb-4751-4301-9a98-f81cb726f3ed.png)
with `ProfileCanvas 0.1.1`, `Pluto v0.19.5` and `julia v1.7.3` (and same with `julia v1.6.5`).

It work normally (real fine) from the REPL (it opens in a firefox tab).

**Comment by ederag** [comment]
Actually, scrolling down, the information is there, but squashed to the right:
![Screenshot_20220528_153026](https://user-images.githubusercontent.com/10962809/170827673-a17b814c-d3d6-4574-a683-65eda6a19713.png)

While with [ProfileSVG](https://github.com/kimikage/ProfileSVG.jl), the profiles starts with the eval (to the left):
![Screenshot_20220528_153121](https://user-images.githubusercontent.com/10962809/170827699-4e8f7893-6b90-429b-a33e-318d8eb63286.png)

**Comment by pfitzseb** [comment]
Not really an issue with this package. Either start Julia single-threaded or use Julia 1.8+ to enable the thread selector.

**Comment by ederag** [comment]
"results in" gave me the impression that the screenshots in the README were expected "out of the box",
and that something was wrong, perhaps due to a Pluto mismatch.
With your explanations (now included in #12), I confirm that it works fine, thanks !
