### ISSUE TITLE
from REPL, firefox is not able to open the generated HTML

### ISSUE THREAD

**Issue by dpinol** [pfitzseb/ProfileCanvas.jl#15]
Hi,
when running from REPL, if the default browser is firefox, the generated html won't be displayed.
Maybe it's a security feature/flag?

This is what I get:

> File not found
> 
> Firefox can’t find the file at /tmp/jl_almvoExR1G.html.
> 
>     Check the file name for capitalization or other typing errors.
>     Check to see if the file was moved, renamed or deleted.

thanks

**Comment by pfitzseb** [comment]
Not sure what to make of that; this works just fine for me with Firefox. Someone else also ran into this issue though.

Can you try monitoring whether that file (well, a html file in `/tmp`  with the `jl_` prefix) is actually created and accessible for you?

**Comment by dpinol** [comment]
> Not sure what to make of that; this works just fine for me with Firefox. Someone else also ran into this issue though.
> 
> Can you try monitoring whether that file (well, a html file in `/tmp` with the `jl_` prefix) is actually created and accessible for you?

yes, it exists and can be correctly displayed with google-chrome. btw, I use ubuntu 21.10 and I have firefox 102 installed with snap.

I guess it's due to this https://bugzilla.mozilla.org/show_bug.cgi?id=1656713 which looks like fixed as per https://bugzilla.mozilla.org/show_bug.cgi?id=1772063

**Comment by pfitzseb** [comment]
Ok, so this is snap specific. Good to know.

Closing this then.
