### ISSUE TITLE
Sometimes flames don't merge

### ISSUE THREAD

**Issue by charleskawczynski** [pfitzseb/ProfileCanvas.jl#16]
I just tried running ProfileCanvas (really nice looking package, btw!), and I noticed that some of the flames are not merging. Here is an example of a flame graph using ChromeProfileFormat.jl and https://profiler.firefox.com/ vs ProfileCanvas.jl (below). The first issue where this is visible is with the `∑tendencies` method, which should be compiled/called for a single set of arguments. `update_aux!` seems to be another one.

<img width="2135" alt="Screen Shot 2022-09-01 at 9 23 18 AM" src="https://user-images.githubusercontent.com/1880641/187965925-9ee1b8ab-8037-4a89-b46d-7aa2529d6385.png">

<img width="2114" alt="Screen Shot 2022-09-01 at 9 19 36 AM" src="https://user-images.githubusercontent.com/1880641/187965926-7943d027-e506-4f44-8603-3b6ca15522c9.png">

**Comment by pfitzseb** [comment]
IIRC merging happens on a line-by-line basis (and judging by the slightly different colors, those are on different lines). Can you upload the HTML somewhere so I can take a look?

**Comment by charleskawczynski** [comment]
Hmm, I can confirm that there's only one `∑tendencies!` definition, but I can upload the html file. Here's a [gist](https://gist.github.com/charleskawczynski/26469a117f0869c904080be6e3afcd51)

**Comment by charleskawczynski** [comment]
I’m starting to think that this is a bug in the profiler, I’ll confirm by retrying this with 1.7, and see if I can open an upstream issue so that we can close this

**Comment by charleskawczynski** [comment]
Strange. On Julia 1.7, using

```julia
import ProfileCanvas
ProfileCanvas.view()
```
and 
```julia
import PProf
PProf.pprof()
```
on the same profile results in unmerged flames with ProfileCanvas and merged flames with PProf. However, using

```julia
lidict = Profile.getdict(unique(Profile.fetch()))

function get_∑tendencies_frames(lidict)
    stack_frames = []
    for key in keys(lidict)
        for sf in lidict[key]
            if sf.func == :∑tendencies!
                push!(stack_frames, sf)
            end
        end
    end
    return stack_frames
end

get_∑tendencies_frames(lidict)[1].line
get_∑tendencies_frames(lidict)[2].line
```
in the same session yields
```julia
julia> get_∑tendencies_frames(lidict)[1].line
231

julia> get_∑tendencies_frames(lidict)[2].line
223
```
So it seems like there is a bug in the profiler, or I'm misinterpreting this `line` field.

**Comment by charleskawczynski** [comment]
Actually, I think everything is fine. It seems like the discrepancy is actually just that the labels of the flames are slightly different than how PProf organizes them:

 - PProf: A flame's label is the (relative) time duration of that function's call
 - ProfileCanvas: a flames's label is a function call in the containing function (i.e., the label)

I'm fine with closing, unless @pfitzseb has a preference between the two?

**Comment by charleskawczynski** [comment]
The way PProf labels the flames makes more sense to me, but that's probably just because I've been looking at them for months 😂

**Comment by charleskawczynski** [comment]
If all of what I said doesn't make sense, then the other way to phrase this is that the multiple `∑tendencies!`'s that show up are function calls inside the `∑tendencies!` definition.

**Comment by charleskawczynski** [comment]
Reflecting on this more, I've come to realize that there's an important distinction between the PProf layout and ProfileCanvas layout. ProfileCanvas's layout actually just displays more information than the PProf layout, and the additional information requires a different label scheme, or (you could say) flames seemingly merge less frequently. Take the (modified) test code, for example:

```julia
using ProfileCanvas

function foo(A)
    m = maximum(A)
    Am = mapslices(sum, A; dims=2)
    B = A[:,:,5]
    Bsort = mapslices(sort, B; dims=1)
    b = rand(size(A, 1))
    C = B.*b
    return maximum(C)
end

function profile_test(n)
    for i = 1:n
        x = foo(randn(100,100,20))
        x = foo(randn(200,200,20))
        x = foo(randn(40,20,20))
    end
end

@profview profile_test(1)  # run once to trigger compilation (ignore this one)
@profview profile_test(10)
```

Visualizing this with PProf yields:

<img width="1933" alt="Screen Shot 2022-09-04 at 11 03 15 AM" src="https://user-images.githubusercontent.com/1880641/188327347-0535d37e-880c-4ffe-aee0-e30231968a04.png">

whereas ProfileCanvas yields

<img width="2178" alt="Screen Shot 2022-09-04 at 10 56 26 AM" src="https://user-images.githubusercontent.com/1880641/188327157-2f6d277a-8d86-4ffa-bb9a-a490bd9905e0.png">

In the PProf version, all `foo` _calls_ are merged together, and you cannot tell the relative expense of the different `foo` calls. In ProfileCanvas, you can because they are split up (by line number).

With this information, I think it's fair to close this issue. It's an interesting difference. I think, overall, this is a superior view of the flame graph. It requires a more careful eye as it provides more information at the expense of (potentially) breaking up flames.

Sorry for all the chatter, some of this was just a reminder for future self. Closing.

**Comment by charleskawczynski** [comment]
For organizational purposes, it might be nice if we could add an flag to (optionally) order of the flames to be alphabetical, so that all of the `foo` calls are at least grouped together.

**Comment by charleskawczynski** [comment]
I suppose we could also add a verbosity flag to optionally provide more/less information so that one of them can match PProf's layout

**Comment by pfitzseb** [comment]
Nice sleuthing! I've opened an issue for those requests :)

FWIW, I'm pretty sure that most of the flame graph visualizers use the same algorithm for display and PProf is the odd one out here.
