### ISSUE TITLE
display multiple profiles simultaneously

### ISSUE THREAD

**Issue by dpinol** [pfitzseb/ProfileCanvas.jl#21]
I'd like to keep the results of multiple profile executions to be able to compare them.
Is it possible?
It looks like everytime that I call @profview it closes the previous flamechart and only the last X/X one is available
![image](https://user-images.githubusercontent.com/1954955/188440757-64f99dfc-8483-4969-b9eb-ea3bb587c66d.png)
I'm not even able to do it by opening 2 different vscode windows because vscode does not allow me to open a project twice :-(

thanks!

**Comment by pfitzseb** [comment]
You can navigate to other profile traces with these buttons
![image](https://user-images.githubusercontent.com/6735977/194032333-a80f508f-eafc-46b6-a5d4-6a8e26c048d3.png)

or the `Julia: Next/Previous Profile` commands.
