### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by gdalle** [pfitzseb/ProfileCanvas.jl#8]
Hi, and thanks for the amazing work!
Following our discussion on Slack, here is a small reminder that registering the package would make it much easier to use with Pluto's built-in package manager. Since my primary use case would be for teaching, it is quite important to ensure broad accessibility.
Feel free to ping me if you need a guinea pig for testing 🐹

**Comment by pfitzseb** [comment]
https://github.com/JuliaRegistries/General/pull/59712
